### ISSUE TITLE
Track website visits data

### ISSUE THREAD

**Issue by dholbach** [fluxcd/stats#2]
We have enabled Netlify Analytics, which gives you some very basic information about how many folks visited the page, but it cuts out at 30 days, so it'd be nice to save this data somewhere.

https://github.com/marketplace/actions/netlify-analytics-collector looks like a good fit - thanks @mewzherder for digging this out.

**Comment by kingdonb** [comment]
I have disabled the parts that connect to Google Drive, I have my own machinery which is in Google Drive and I'm looking at optimal ways to integrate it. (If we have a machine account or an app, that will make it smoother, but I've been using a "dev" Google App for my Flux Bug Scrub sheet generation for some time, and it has test scaffolds built around it to some extent...)
